apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-blog
  namespace: argocd
spec:
  destination:
    namespace: wevans
    server: "{{ .Values.spec.destination.server }}"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  project: wevans
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data/postgres-password
  source:
    path: charts
    repoURL: https://github.com/wevanscfi/blog.git
    targetRevision: main
    helm:
      parameters:
        - name: image.tag
          value: "3d19f7aca071d0ccd7c14d533d7b3342f16e3f65"
        - name: ingress.enabled
          value: 'true'
        - name: ingress.className
          value: nginx
        - name: ingress.hosts[0].host
          value: rails.{{ .Values.spec.cluster.baseDomain }}
        - name: ingress.tls[0].hosts[0]
          value: rails.{{ .Values.spec.cluster.baseDomain }}
        - name: ingress.tls[0].secretName
          value: blog-tls
        - name: ingress.issuer
          value: letsencrypt
        - name: application.env.base_host
          value: blog.gke.wevans.io
      valueFiles:
        - values.yaml
