apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog
  namespace: argocd
spec:
  destination:
    namespace: wevans
    server: "{{ .Values.spec.destination.server }}"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: wevans
  source:
    path: charts
    repoURL: https://github.com/wevanscfi/blog.git
    targetRevision: main
    helm:
      parameters:
        - name: image.tag
          value: "8421152a7e55a8693cd74f8ee58674bebe4b4b14"
        - name: ingress.enabled
          value: 'true'
        - name: ingress.className
          value: nginx
        - name: ingress.hosts[0].host
          value: rails.{{ .Values.spec.cluster.baseDomain }}
        - name: ingress.tls[0].hosts[0]
          value: rails.{{ .Values.spec.cluster.baseDomain }}
        - name: ingress.tls[0].secretName
          value: blog-tls
        - name: ingress.issuer
          value: letsencrypt
        - name: application.env.base_host
          value: rails.gke.wevans.io
      valueFiles:
        - values.yaml
