apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-cleaner
  namespace: argocd
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: pod-cleaner
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: cluster-services
  source:
    path: charts/pod-cleaner
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
