apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: cluster-services
  source:
    path: charts/prometheus
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      skipCrds: true
      parameters:
        - name: grafana.envFromSecret
          value: grafana-oauth
        - name: grafana.grafana.ini
          value: |
            [auth.github]
            enabled = true
            scopes = user:email,read:org
            auth_url = https://github.com/login/oauth/authorize
            token_url = https://github.com/login/oauth/access_token
            api_url = https://api.github.com/user
            allow_sign_up = true
            allowed_organizations = wevanshomelab
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
spec:
  project: cluster-services
  source:
    path: charts/kube-prometheus-stack/crds
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: kube-prometheus-stack-43.1.1
    helm:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-bootstrap
  namespace: argocd
spec:
  project: cluster-services
  source:
    path: charts/grafana-bootstrap
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
