apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
spec:
  project: cluster-services
  source:
    repoURL: https://kubernetes-charts.banzaicloud.com
    chart: vault-operator
    targetRevision: 1.18.0
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: vault
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: cluster-services
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.23.0
    helm:
      parameters:
        - name: server.affinity
          value: ""
        - name: server.ha.enabled
          value: "true"
        - name: server.annotations.linkerd\.io\/inject
          value: enabled
        - name: server.ha.raft.config
          value: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "raft" {
              path = "/vault/data"
              retry_join {
                leader_api_addr = "http://vault-0.vault-internal:8200"
              }
              retry_join {
                leader_api_addr = "http://vault-1.vault-internal:8200"
              }
              retry_join {
                leader_api_addr = "http://vault-2.vault-internal:8200"
              }
            }
            service_registration "kubernetes" {}
            seal "gcpckms" {
               project     = "{{ .Values.spec.gcpProject }}"
               region      = "global"
               key_ring    = "vault-keyring-b8da431"
               crypto_key  = "vault-key-0e0b4d1"
            }
        - name: server.ha.raft.enabled
          value: "true"
        - name: server.serviceAccount.annotations.iam\.gke\.io\/gcp-service-account
          value: vault-gcpkms@{{ .Values.spec.gcpProject }}.iam.gserviceaccount.com
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
