apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
spec:
  project: cluster-services
  source:
    repoURL: https://kubernetes-charts.banzaicloud.com
    chart: vault-operator
    targetRevision: 1.18.0
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: vault
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: cluster-services
  source:
    path: charts/vault
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: server.annotations.linkerd\.io\/inject
          value: enabled
        - name: gcp.keyRing
          value: vault-keyring-b8da431
        - name: gcp.cryptoKey
          value: vault-key-0e0b4d1
        - name: gcp.location
          value: global
        - name: gcp.project
          value: {{ .Values.spec.gcpProject }}
        - name: gcp.serviceAccount
          value: vault-gcpkms@{{ .Values.spec.gcpProject }}.iam.gserviceaccount.com
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  #ignoreDifferences:
    #- group: admissionregistration.k8s.io
      #kind: ValidatingWebhookConfiguration
      #jqPathExpressions:
        #- .webhooks[]?.clientConfig.caBundle
    #- group: admissionregistration.k8s.io
      #kind: MutatingWebhookConfiguration
      #jqPathExpressions:
        #- .webhooks[]?.clientConfig.caBundle
