apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog
  namespace: argocd
spec:
  destination:
    namespace: test
    server: "{{ .Values.spec.destination.server }}"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: applications
  source:
    path: charts
    repoURL: https://github.com/wevanscfi/blog.git
    targetRevision: main
    helm:
      parameters:
        - name: image.tag
          value: "e7591bcfc093c50e9f4fe9aaf1c0a8676499e21e"
        - name: ingress.hosts[0].host
          value: rails.localhost
      valueFiles:
        - values.yaml
        - dev-values.yaml
