apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: gitlab
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    chart: gitlab
    repoURL: https://charts.gitlab.io
    targetRevision: 6.7.3
