kube-prometheus-stack:
  prometheusOperator:
    admissionWebhooks:
      patch:
        enabled: false
      failurePolicy: Fail
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false
  nodeExporter:
    enabled: true
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - grafana.gke.wevans.io
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.gke.wevans.io
    envFromSecrets:
      - name: grafana-oauth
    grafana.ini:
      server:
        root_url: https://grafana.gke.wevans.io
      auth.github:
        enabled: true
        allow_sign_up: true
        scopes: user:email,read:org
        auth_url: https://github.com/login/oauth/authorize
        token_url: https://github.com/login/oauth/access_token
        api_url: https://api.github.com/user
        allowed_organizations: wevanshomelab
        role_attribute_path: contains(groups[*], '@wevanshomelab/admins') && 'Admin' || 'Viewer'
        allow_assign_grafana_admin: true
