kube-prometheus-stack:
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false
  nodeExporter:
    enabled: true
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - grafana.gke.wevans.io
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.gke.wevans.io

