ingress-nginx:
  controller:
    podAnnotations:
      linkerd.io/inject: enabled
    extraArgs:
      enable-ssl-passthrough: true
    service:
      type: NodePort
    admissionWebhooks:
      enabled: false

