ingress-nginx:
  controller:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - ingress-nginx
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - ingress
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - controller
            topologyKey: topology.kubernetes.io/zone
    resources:
      requests:
        cpu: 20m
    replicaCount: 3
    podAnnotations:
      linkerd.io/inject: enabled
    extraArgs:
      enable-ssl-passthrough: true
    admissionWebhooks:
      enabled: false

