---
argocd-apps:
  projects:
    - name: argocd
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      description: Argocd Project
      sourceRepos:
        - '*'
      destinations:
        - namespace: argocd
          server: https://kubernetes.default.svc
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      orphanedResources:
        warn: false
    - name: wevans
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      description: User Applications
      sourceRepos:
        - '*'
      destinations:
        - namespace: wevans
          server: https://kubernetes.default.svc
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      orphanedResources:
        warn: false
    - name: cluster-services
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      description: Core Cluster Services
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      orphanedResources:
        warn: false
  applications:
    - name: wevans
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: manifests/wevans
        repoURL: https://github.com/wevanscfi/homelab.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
    - name: cluster-services
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: manifests/cluster
        repoURL: https://github.com/wevanscfi/homelab.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
    - name: argocd
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: manifests/argocd
        repoURL: https://github.com/wevanscfi/homelab.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true

