---
argocd-apps:
  projects:
    - name: argocd
      namespace: argocd
      description: Argocd Project
      sourceRepos:
        - '*'
      destinations:
        - namespace: argocd
          server: https://kubernetes.default.svc
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      orphanedResources:
        warn: false
    - name: cluster-services
      namespace: argocd
      description: Core Cluster Services
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      orphanedResources:
        warn: false
  applications:
    - name: argocd
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: charts/argocd
        repoURL: https://github.com/wevanscfi/homelab.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
    - name: argocd-apps
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: charts/argocd-apps
        repoURL: https://github.com/wevanscfi/homelab.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
    - name: user-projects
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: charts/user-projects
        repoURL: https://github.com/wevanscfi/homelab.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
    - name: cluster-services
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: manifests/cluster-services
        repoURL: https://github.com/wevanscfi/homelab.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true

