linkerd-control-plane:
  proxyInit:
    privileged: true
    runAsRoot: true
    resources:
      cpu:
        request: ""
        limit: ""
  identityTrustAnchorsPEM: |-
    -----BEGIN CERTIFICATE-----
    MIIBjTCCATOgAwIBAgIQTeR50Zqr0MW7OGL7JXlyIzAKBggqhkjOPQQDAjAlMSMw
    IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMzAxMjYxOTIy
    MjdaFw0yODAxMjUxOTIyMjdaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
    dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAER6ss8bogHoYT6ddT
    hS4CR3ykQAzj/wtF04CYUiwm57Q+do3KAaLCzmlvt3xtfk+xi+ByjMQILY7Fkea3
    b46/AqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
    VR0OBBYEFFWCphg01gFaI2SzKd2OscwKnNpSMAoGCCqGSM49BAMCA0gAMEUCIBuv
    Lx6+XLyFLWSpIGQt+963spmE0/HRAPImfpjwtDmSAiEAkpP/ug5u3S6rncPRs84X
    PQFx8VLOWd8p9qn9SVaoz3A=
    -----END CERTIFICATE-----
  identity:
    issuer:
      scheme: kubernetes.io/tls
