linkerd-control-plane:
  proxyInit:
    privileged: true
    runAsRoot: true
    resources:
      cpu:
        request: ""
        limit: ""
  identityTrustAnchorsPEM: |-
    -----BEGIN CERTIFICATE-----
    MIIBjTCCATSgAwIBAgIRANLeKu18fozWIJPQHrup1yswCgYIKoZIzj0EAwIwJTEj
    MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjMxMTA5MTQy
    ODM2WhcNMjgxMTA3MTQyODM2WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
    c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABAX/BoqpAAriI2rD
    ZJt031y4DrmkvKbDhvVw3SQ61OXH7zBo5GM3p+25Tc7LqY4QD27hrkaT/1u4ihgn
    iJR36/OjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
    A1UdDgQWBBRf3egyusRcXrFfnzvWiubyf4nnZjAKBggqhkjOPQQDAgNHADBEAiAP
    mXSWZO0h0y1JijvH2LreWIjPbfX15eMDFV8eIqOR8wIgSfHYbMyLCL4NgJVQtZQO
    q6hufN9wHj3b1nNQAKWTQjc=
    -----END CERTIFICATE-----
  identity:
    issuer:
      scheme: kubernetes.io/tls
