apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-service
  namespace: argocd
spec:
  project: argocd
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    helm:
      version: v3
      valueFiles:
      - values.yaml
      parameters
      - name: "argo-cd.server.ingress.hosts[0]"
        value: "argocd.{{ .Values.spec.cluster.baseDomain }}"
    path: charts/argocd
    repoURL: https://github.com/wevanscfi/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
