apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
spec:
  size: 3
  image: vault:0.10.1
  bankVaultsImage: banzaicloud/bank-vaults:master
  serviceAccount: vault
  unsealConfig:
    google:
      kmsKeyRing: {{ .Values.gcp.keyRing }}
      kmsCryptoKey: {{ .Values.gcp.cryptoKey }}
      kmsLocation: {{ .Values.gcp.location }}
      kmsProject: {{ .Values.gcp.project }}
      storageBucket: {{ .Values.gcp.storageBucket }}
  config:
    storage:
      gcs:
        bucket: {{ .Values.gcp.storageBucket }}
        ha_enabled: "true"
      listener:
        tcp:
          address: "0.0.0.0:8200"
      api_addr: http://vault.default:8200
      ui: true
