apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
spec:
  size: 3
  image: vault:0.10.1
  bankVaultsImage: banzaicloud/bank-vaults:master
  serviceAccount: vault
  unsealConfig:
    google:
      kmsKeyRing: {{ .Values.gcp.keyRing }}
      kmsCryptoKey: {{ .Values.gcp.cryptoKey }}
      kmsLocation: {{ .Values.gcp.location }}
      kmsProject: {{ .Values.gcp.project }}
      storageBucket: {{ .Values.gcp.storageBucket }}
  config:
    storage:
      gcs:
        bucket: {{ .Values.gcp.storageBucket }}
        ha_enabled: "true"
    listener:
      tcp:
        address: "[::]:8200"
        cluster_address: "[::]:8201"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault:8200
    ui: true
  externalConfig:
    policies:
      - name: admin
        rules: |
          # Read all
          path "*"
          {
            capabilities = ["read", "list"]
          }

          # Read system health check
          path "sys/health"
          {
            capabilities = ["read", "sudo"]
          }

          # Create and manage ACL policies broadly across Vault

          # List existing policies
          path "sys/policies/acl"
          {
            capabilities = ["list"]
          }

          # Create and manage ACL policies
          path "sys/policies/acl/*"
          {
            capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }

          # Enable and manage authentication methods broadly across Vault

          # Manage auth methods broadly across Vault
          path "auth/*"
          {
            capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }

          # Create, update, and delete auth methods
          path "sys/auth/*"
          {
            capabilities = ["create", "update", "delete", "sudo"]
          }

          # List auth methods
          path "sys/auth"
          {
            capabilities = ["read"]
          }

          # Enable and manage the key/value secrets engine at `secret/` path

          # List, create, update, and delete key/value secrets
          path "secret/*"
          {
            capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }

          # Manage secrets engines
          path "sys/mounts/*"
          {
            capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }

          # List existing secrets engines.
          path "sys/mounts"
          {
            capabilities = ["read"]
          }
      - name: allow_all_secrets
        rules: |
          path "secret/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: allow_user_secrets
        rules: |
          path "{{ printf "secret/data/{{identity.entity.id}}/*" }}" {
            capabilities = ["create", "update", "patch", "read", "delete"]
          }
          path "{{ printf "secret/metadata/{{identity.entity.id}}/*" }}" {
            capabilities = ["list"]
          }
    auth:
      - type: github
        options:
          listing_visibility: "unauth"
        config:
          organization: wevanshomelab
        map:
          teams:
            admins: admin
            users: allow_user_secrets
      - type: kubernetes
        roles:
          - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: default
            policies: allow_user_secrets
            ttl: 1h
    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2
