spec:
  cluster:
    baseDomain: gke.wevans.io
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/wevanshomelab/gke-cluster.git
    targetRevision: main
