---
## ArgoCD configuration
## Ref: https://github.com/argoproj/argo-cd
##
## Server
argo-cd:
  server:
    certificate:
      enabled: true
      domain: argocd.gke.wevans.io
      issuer:
        kind: ClusterIssuer
        name: letsencrypt
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: true
        nginx.ingress.kubernetes.io/ssl-passthrough: true
      ingressClassName: nginx
      hosts:
        - argocd.gke.wevans.io
    configEnabled: true
    config:
      url: "https://argocd.gke.wevans.io"
      repositories: |
        - type: git
          url: https://github.com/wevanshomelab/gke-cluster.git
        - name: argo-helm
          type: helm
          url: https://argoproj.github.io/argo-helm
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: fe519b758cce7aa69b42
              clientSecret: $dex.github.clientSecret
              orgs:
                - name: wevanshomelab
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, wevanshomelab:admins, role:admin
        g, wevanshomelab:users, role:readonly

