---
## ArgoCD configuration
## Ref: https://github.com/argoproj/argo-cd
##
## Server
argo-cd:
  server:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: true
        nginx.ingress.kubernetes.io/ssl-passthrough: true
      ingressClassName: nginx
      hosts:
        - argocd.localhost
    ## ArgoCD config
    ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
    configEnabled: true
    config:
      repositories: |
        - type: git
          url: https://github.com/wevanscfi/homelab.git
        - name: argo-helm
          type: helm
          url: https://argoproj.github.io/argo-helm
  configs:
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: 1f8518c59d564db08774
            clientSecret: $dex.github.clientSecret
            orgs:
              - name: WevansHomeLab

